### ISSUE TITLE
Invalid URI "NaN/customer/1"

### ISSUE THREAD

**Issue by blurp1478963** [mcohen01/node-quickbooks#121]
Hi!

using:

```js
  qbo = new QuickBooks({
    consumerKey: process.env.QBO_CONSUMER_KEY,
    consumerSecret: process.env.QBO_CONSUMER_SECRET,
    token: accessToken.token,
    tokenSecret: false,
    realmId: process.env.QBO_REALM_ID,
    useSandbox: process.env.QBO_SANDBOX,
    debug: process.env.QBO_DEBUG,
    minorversion: process.env.QBO_MINOR_VERSION,
    oauthversion: '2.0',
    refreshToken: accessToken.refresh_token,
  })
```

I'm facing this issue: 

```bash
(node:3763) UnhandledPromiseRejectionWarning: Error: Invalid URI "NaN/customer/1"
    at Request.init (./node_modules/request/request.js:273:31)
    at new Request (./node_modules/request/request.js:127:8)
    at request (./node_modules/request/index.js:53:10)
    at Object.<anonymous> (./node_modules/request/index.js:61:12)
    at Module.module.request (./node_modules/node-quickbooks/index.js:2374:17)
    at Module.module.read (./node_modules/node-quickbooks/index.js:2445:10)
    at Object.QuickBooks.getCustomer (./node_modules/node-quickbooks/index.js:690:10)
    at Promise (internal/util.js:276:30)
    at new Promise (<anonymous>)
    at Object.getCustomer (internal/util.js:275:12)
    at Object.eval (webpack:///./src/queue/qbo.queue.events/hook.create.customer.ts?:13:44)
    at Generator.next (<anonymous>)
    at eval (webpack:///./src/queue/qbo.queue.events/hook.create.customer.ts?:7:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack:///./src/queue/qbo.queue.events/hook.create.customer.ts?:3:12)
    at Object.exports.default [as eventQboAddedClient] (webpack:///./src/queue/qbo.queue.events/hook.create.customer.ts?:12:36)
(node:3763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

on `getCustomer` method

The tokens / refresh tokens are valid (generated from playground)

Do you have an idea?

Thanks by advance!

Ben

**Comment by nthornton2010** [comment]
This was happening to me when I tried to wrap a method in util.promisify (was wrapping and calling createInvoice). I ended up using bluebird to get around it. It didn't happen on normal method calls though.

**Comment by toverux** [comment]
Yes, same happened to me but that's our fault, not util.promisify's one. This is because, by doing `util.promisify(qb.findSomething)`, the function looses `this` scope (JavaScript uses late `this` binding, at call time).
It's like you were doing `const findSomething = qb.findSomething; findSomething()`: you'll get the same result.
You'd have to do `util.promisify(qb.findSomething.bind(qb))` to make it work.
I don't know how Bluebird makes to bind this correctly though, probably some dark magic or a probably it makes you use quite a different syntax? Anyway, that's a language problem, the library is fine here.
