### ISSUE TITLE
Breaking change in 2.0.36

### ISSUE THREAD

**Issue by YasharF** [mcohen01/node-quickbooks#169]
Going from 2.0.34 to 2.0.36 is turning out to be a breaking change.  The following code has been working for quite some time, but when upgrading node-quickbooks from 2.0.34 to 2.0.36, it gives out errors.  Can you please revert the change, or if it is a breaking change make a new major version and document what we need to do to upgrade to this version?  Thank you.

```
exports.getQuickbooks = (req, res) => {
  const token = req.user.tokens.find((token) => token.kind === 'quickbooks');

  const qbo = new Quickbooks(process.env.QUICKBOOKS_CLIENT_ID, process.env.QUICKBOOKS_CLIENT_SECRET,
    token.accessToken, false, req.user.quickbooks, true, false, null, '2.0', token.refreshToken);

  qbo.findCustomers((_, customers) => {
    res.render('api/quickbooks', {
      title: 'Quickbooks API',
      customers: customers.QueryResponse.Customer
    });
  });
};
```
Full source at https://github.com/sahat/hackathon-starter/blob/master/controllers/api.js#L135
The code with 2.0.34 is live on a public demo server at https://hackathon-starter.walcony.com/api/quickbooks

**Error when upgrading 2.0.34 to 2.0.36:**
```
2020-10-07T19:37:28.856839+00:00 app[web.1]: SyntaxError: Unexpected token u in JSON at position 02020-10-07T19:37:28.856848+00:00 app[web.1]: at JSON.parse (<anonymous>)
2020-10-07T19:37:28.856849+00:00 app[web.1]: at Module.module.query (/app/node_modules/node-quickbooks/index.js:2409:31)
2020-10-07T19:37:28.856849+00:00 app[web.1]: at QuickBooks.findCustomers (/app/node_modules/node-quickbooks/index.js:1634:10)
2020-10-07T19:37:28.856850+00:00 app[web.1]: at exports.getQuickbooks (/app/controllers/api.js:141:7)
2020-10-07T19:37:28.856850+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-10-07T19:37:28.856851+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-10-07T19:37:28.856851+00:00 app[web.1]: at exports.isAuthorized (/app/config/passport.js:767:7)
2020-10-07T19:37:28.856851+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-10-07T19:37:28.856852+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-10-07T19:37:28.856852+00:00 app[web.1]: at exports.isAuthenticated (/app/config/passport.js:720:12)
2020-10-07T19:37:28.856853+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-10-07T19:37:28.856853+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/route.js:137:13)
2020-10-07T19:37:28.856853+00:00 app[web.1]: at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2020-10-07T19:37:28.856854+00:00 app[web.1]: at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2020-10-07T19:37:28.856854+00:00 app[web.1]: at /app/node_modules/express/lib/router/index.js:281:22
2020-10-07T19:37:28.856854+00:00 app[web.1]: at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2020-10-07T19:37:28.856855+00:00 app[web.1]: at next (/app/node_modules/express/lib/router/index.js:275:10)
2020-10-07T19:37:28.856855+00:00 app[web.1]: at SendStream.error (/app/node_modules/serve-static/index.js:121:7)
2020-10-07T19:37:28.856856+00:00 app[web.1]: at SendStream.emit (events.js:314:20)
2020-10-07T19:37:28.856856+00:00 app[web.1]: at SendStream.error (/app/node_modules/send/index.js:270:17)
2020-10-07T19:37:28.856856+00:00 app[web.1]: at SendStream.onStatError (/app/node_modules/send/index.js:421:12)
2020-10-07T19:37:28.856857+00:00 app[web.1]: at next (/app/node_modules/send/index.js:735:16)
2020-10-07T19:37:28.856857+00:00 app[web.1]: at onstat (/app/node_modules/send/index.js:724:14)
2020-10-07T19:37:28.856858+00:00 app[web.1]: at FSReqCallback.oncomplete (fs.js:177:21)
```

**Comment by mcohen01** [comment]
Sorry about that. Fixed in `2.0.37`
