### ISSUE TITLE
SyncToken 0 error

### ISSUE THREAD

**Issue by shizy** [mcohen01/node-quickbooks#29]
First, thanks for the great work on this!
In the README provided, SyncToken on an Update is defined as an integer. 
However, if the SyncToken should be 0, I'm getting the following error when defining 0 as an Int:
```
/home/shizy/dev/nhubackend/node_modules/node-quickbooks/index.js:1794
    throw new Error(entityName + ' must contain Id and SyncToken fields: ' +
    ^

Error: customer must contain Id and SyncToken fields: { Id: 5882,
  SyncToken: 0,
  sparse: true,
  PreferredDeliveryMethod: 'Email' }
    at Module.module.update (/home/shizy/dev/nhubackend/node_modules/node-quickbooks/index.js:1794:11)
    at QuickBooks.updateCustomer (/home/shizy/dev/nhubackend/node_modules/node-quickbooks/index.js:869:10)
    at /home/shizy/dev/nhudeposits/index.js:6:12
    at Request._callback (/home/shizy/dev/nhubackend/index.js:44:20)
    at Request.self.callback (/home/shizy/dev/nhubackend/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/shizy/dev/nhubackend/node_modules/request/request.js:1082:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
```
When changing the SyncToken to "0" (string), the update is sucessful. I can only guess that 0 (int) is being interpreted as false during a SyncToken check?

**Comment by mcohen01** [comment]
Thanks!  Should be fixed in 1.0.26.
